# This file should be placed in your home directory

autoloaders:
  # Namespace => path to your libs
  ProjectEight: /Users/projecteight/PhpStormProjects/projecteight-magerun/src

twig:
  baseDirs:
    - /Users/projecteight/PhpStormProjects/projecteight-magerun/res/twig/

commands:
  customCommands:
    - ProjectEight\Magento\Command\Developer\Generate\ModuleCommand
    - ProjectEight\Magento\Command\Eav\Attribute\AddCommand
    - ProjectEight\Magento\Command\Developer\Environment\SetCommand
    - ProjectEight\Magento\Command\Developer\Module\Create\BetterCommand
    - ProjectEight\Magento\Command\Developer\Toggle\ShippingMethodCommand
    - ProjectEight\Magento\Command\System\ReportCommand

  ProjectEight\Magento\Command\System\ReportCommand:
    reports:
      system:
        - ProjectEight\Magento\Command\System\Report\System\VersionReport
        - ProjectEight\Magento\Command\System\Report\System\EditionReport
        - ProjectEight\Magento\Command\System\Report\System\CacheReport
      payments:
        - ProjectEight\Magento\Command\System\Report\Payments\PaymentMethodsReport
      shipping:
        - ProjectEight\Magento\Command\System\Report\Shipping\ShippingMethodsReport
      patches:
        - ProjectEight\Magento\Command\System\Report\Patches\AppliedReport
      overrides:
        - ProjectEight\Magento\Command\System\Report\Overrides\LocalReport

  ProjectEight\Magento\Command\Developer\Environment\SetCommand:
    environments:
      localhost:
        config:
          default:
            0:
              general/country/default: GB
              general/store_information/merchant_country: FR
              design/head/demonotice: 1
              trans_email/ident_general/email: projecteight@example.com
              trans_email/ident_sales/email: projecteight@example.com
              trans_email/ident_support/email: projecteight@example.com
              trans_email/ident_custom1/email: projecteight@example.com
              trans_email/ident_custom2/email: projecteight@example.com
              contacts/email/recipient_email: projecteight@example.com
              sitemap/generate/error_email: projecteight@example.com
              customer/password/require_admin_user_to_change_user_password: 0
              tax/defaults/country: GB
              tax/defaults/postcode: "YO24 1BF"
              shipping/origin/country_id: GB
              shipping/origin/region_id: North Yorkshire
              shipping/origin/postcode: "YO24 1BF"
#              Shipping methods:
              carriers/dhlint/active: 0
              carriers/dhl/active: 0
              carriers/fedex/active: 0
              carriers/usps/active: 0
              carriers/ups/active: 0
              google/analytics/account: UA-123456-AB
              payment/account/merchant_country: GB
              # PayPal Express Checkout:
#              payment/express_checkout_required_express_checkout/business_account
#              payment/express_checkout_required_express_checkout/api_authentication
#              payment/express_checkout_required_express_checkout/api_username
#              payment/express_checkout_required_express_checkout/api_password
#              payment/express_checkout_required_express_checkout/api_signature
#              payment/express_checkout_required_express_checkout/sandbox_flag
#              payment/express_checkout_required/enable_express_checkout: 0
              payment/settings_ec/payment_action: Sale
              payment/settings_ec_advanced/debug: 1
#              Other payment methods:
              payment/checkmo/active: 1
              payment/checkmo/specificcountry: GB,DE
              admin/security/extensions_compatibility_mode: Disabled
              system/smtp/disable: 1
              dev/log/active: 1
              dev/restrict/allow_ips: 127.0.0.1
      dev:
        config:
          websites:
            1:
              general/country/default: FR
          stores:
            3:
              general/country/default: DE

  ProjectEight\Magento\Command\Developer\Module\Create\BetterCommand:
    additionalFiles:
      "dev/module/create/app/Helper/Data.twig": "{{moduleDir}}/Helper/Data.php"
      "dev/module/create/app/data/data-install-0.1.0.twig": "{{moduleDir}}/data/{{ vendorNamespace | lower }}_{{ moduleName | lower }}_setup/data-install-0.1.0.php"
      "dev/module/create/app/sql/install-0.1.0.twig": "{{moduleDir}}/sql/{{ vendorNamespace | lower }}_{{ moduleName | lower }}_setup/install-0.1.0.php"

  N98\Magento\Command\Installer\InstallCommand:
    magento-packages:
      - name: magento-local-1.9.2.4
        version: 1.9.2.4
        dist:
          url: http://magento.local/versions/magento-1.9.2.4.tar.gz
          type: tar
        extra:
          sample-data: sample-data-local-1.9.0.0
    demo-data-packages:
      - name: sample-data-local-1.9.0.0
        version: 1.9.0.0
        dist:
          url: http://magento.local/extras/sample-data/magento-sample-data-1.9.0.0.tar.gz
          type: tar
    installation:
      defaults:
        currency: GBP
        locale: en_GB
        timezone: Europe/London
        use_secure: no
        use_rewrites: yes
        session_save: files
        admin_username: admin
        admin_firstname: Joe
        admin_lastname: Bloggs
        admin_password: password123
        admin_frontname: admin
        admin_email: projecteight@example.com
        encryption_key: