# This file should be placed in your home directory

autoloaders:
  # Namespace => path to your libs
  sfrost2004: /Users/simonfrost/PhpStormProjects/sfrost2004/src

commands:
  customCommands:
    - sfrost2004\Magento\Command\Developer\Module\Create\BetterCommand

  # optional command config
  #MyCommandNamespace\FooCommand:
  #  foo: bar

twig:
  baseDirs:
    - /Users/simonfrost/PhpStormProjects/magerun/res/twig/